http:
  port: 8080
apiEndpoints:
  be1:
    host: "*"
    paths: "/api/be1/*"
  be2:
    host: "*"
    paths: "/api/be2/*"
serviceEndpoints:
  be1:
    url: "http://backend1-service:3000"
  be2:
    url: "http://backend2-service:3001"

policies:
  - cors
  #  - expression
  #  - log
  - proxy
pipelines:
  - name: be1
    apiEndpoints:
      - be1
    policies:
      - proxy:
          - action:
              serviceEndpoint: be1
              changeOrigin: true
  - name: be2
    apiEndpoints:
      - be2
    policies:
      - proxy:
          - action:
              serviceEndpoint: be2
              changeOrigin: true
